### ISSUE TITLE
Create new SyllabusElement - Question to SyllabusElement Relation MUST be empty

### ISSUE THREAD

**Issue by BPMspace** [BPMspaceUG/SQMS#7]

**Comment by BPMspace** [comment]
![sqms_bug_new_se](https://cloud.githubusercontent.com/assets/5494549/24743150/7ad732ca-1aad-11e7-9e34-91816041bd94.PNG)

**Comment by dwu300** [comment]
Solved by not showing the Linklist during creation of the Syllabus Element,
because not ID is yet created - therefore no assignment can be made.
Only after creation of the SyllabusElement it is possible.
